apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gltonyy7z-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:77ca9262bb77bc1eb11c584047d24cd74c3764bd@sha256:ef9b9cc84103fa7e1b07a2d9016e6f4ed26f6af280cc108b3ae671c54e8ec0df
          name: container-image
